-- Material You window-border colours -> regenerated by matugen on every wallpaper change
-- (rotate_wallpaper.sh runs `matugen image`, which processes every template in config.toml).
-- Consumed by hypr/modules/looknfeel.lua via dofile(); returns the active-border gradient
-- stops: { tertiary, primary }. Angle is kept in looknfeel.lua (45deg).
return { "rgb({{colors.tertiary.default.hex_stripped}})", "rgb({{colors.primary.default.hex_stripped}})" }
