# LS_COLORS overrides -> regenerated by matugen on every wallpaper change
# (rotate_wallpaper.sh runs `matugen image`, which processes every template in config.toml).
# Sourced from .zshrc, appended after `dircolors -b`'s stock defaults.
#
# Why this exists: GNU ls's stock LS_COLORS hardcodes `ow` (world-writable dir) as
# "34;42" - blue text on green background. The ghostty theme remaps ANSI slot 4 (blue)
# to the wallpaper's primary color for prompt/tool legibility elsewhere, but leaves slot 2
# (green) fixed for lazydocker/lazygit/btop semantics (see ghosttyTemplate.conf). When the
# wallpaper's primary happens to be pale, that combo becomes pale-on-green and unreadable
# (e.g. world-writable folders under a 777 backup dir). Using true-color (38;2;r;g;b)
# theme pairs here sidesteps the ANSI remap entirely and keeps guaranteed contrast via
# matugen's on_* roles, regardless of what the current wallpaper's accent looks like.
LS_COLORS="${LS_COLORS}:ow=1;38;2;{{ colors.on_tertiary.default.red }};{{ colors.on_tertiary.default.green }};{{ colors.on_tertiary.default.blue }};48;2;{{ colors.tertiary.default.red }};{{ colors.tertiary.default.green }};{{ colors.tertiary.default.blue }}"
LS_COLORS="${LS_COLORS}:tw=1;38;2;{{ colors.on_tertiary.default.red }};{{ colors.on_tertiary.default.green }};{{ colors.on_tertiary.default.blue }};48;2;{{ colors.tertiary.default.red }};{{ colors.tertiary.default.green }};{{ colors.tertiary.default.blue }}"
LS_COLORS="${LS_COLORS}:st=1;38;2;{{ colors.on_primary.default.red }};{{ colors.on_primary.default.green }};{{ colors.on_primary.default.blue }};48;2;{{ colors.primary.default.red }};{{ colors.primary.default.green }};{{ colors.primary.default.blue }}"
export LS_COLORS
