general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd =                                   # let hyprlock exit on its own
    before_sleep_cmd = loginctl lock-session       # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on     # avoid pressing a key twice to wake the display
}

listener {
    timeout = 300                      # 5 min idle -> lock
    on-timeout = loginctl lock-session
}

listener {
    timeout = 360                                            # TOOO: this is not working right now -> 6 min idle -> screen off 
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen + brightness back on activity
}
