# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1dd67c82-10eb-408b-8fb8-75b182ca9fe0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/69BF-2892";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Swapfile persistant pour l'hibernation (mise en veille prolongée, façon
  # Windows). zramSwap (configuration.nix) reste utilisé pour le swap
  # quotidien (volatile, RAM compressée) ; ce fichier sert uniquement de
  # cible d'écriture pour l'image mémoire au moment de `systemctl hibernate`.
  # Taille = 34G, un peu au-dessus des 32G de RAM de la machine (marge de
  # sécurité). boot.resumeDevice / boot.kernelParams (resume_offset) dans
  # configuration.nix pointent dessus une fois le fichier créé sur disque.
  swapDevices = [
    { device = "/var/lib/swapfile"; size = 34 * 1024; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
